services:
  #mongoDB services
  mongoDB: #name of service and a container for mongodb container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_DB:/data/db

  #rest API with node.js
  node_api: #name of service and container name
    build: . #poišče dockerfile v istem folderju v katerem se nahaja docker-compose
    ports:
      - 5000:5000
    volumes:
      - .:/user/src/app
    environment:
      PORT: 5000
      MONGO_URI: mongodb+srv://aljosakorosec123:geslo123@node-app-shop.otmghlo.mongodb.net/?retryWrites=true&w=majority
      DB_NAME: mongo_db
    depends_on:
      - mongoDB #depends on the database-->name in the upper code
      
volumes:
  mongo_DB:
    driver: local # sem se shranjuje data-->locally on the hosts computer

    